// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: stream_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StreamManager_StartStream_FullMethodName          = "/stream_service.StreamManager/StartStream"
	StreamManager_Heartbeat_FullMethodName            = "/stream_service.StreamManager/Heartbeat"
	StreamManager_StopStream_FullMethodName           = "/stream_service.StreamManager/StopStream"
	StreamManager_UpdateSessionMetrics_FullMethodName = "/stream_service.StreamManager/UpdateSessionMetrics"
	StreamManager_UpdateStreamMetadata_FullMethodName = "/stream_service.StreamManager/UpdateStreamMetadata"
	StreamManager_GetLiveStreams_FullMethodName       = "/stream_service.StreamManager/GetLiveStreams"
	StreamManager_GetStream_FullMethodName            = "/stream_service.StreamManager/GetStream"
)

// StreamManagerClient is the client API for StreamManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamManagerClient interface {
	// --- Lifecycle (Ingest/Processing) ---
	StartStream(ctx context.Context, in *StartStreamRequest, opts ...grpc.CallOption) (*StartStreamResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	StopStream(ctx context.Context, in *StopStreamRequest, opts ...grpc.CallOption) (*StopStreamResponse, error)
	// Allows Ingest/Processing to update resolution/bitrate mid-stream
	UpdateSessionMetrics(ctx context.Context, in *UpdateSessionMetricsRequest, opts ...grpc.CallOption) (*UpdateSessionMetricsResponse, error)
	// --- User Actions ---
	UpdateStreamMetadata(ctx context.Context, in *UpdateMetadataRequest, opts ...grpc.CallOption) (*UpdateMetadataResponse, error)
	GetLiveStreams(ctx context.Context, in *GetLiveStreamsRequest, opts ...grpc.CallOption) (*GetLiveStreamsResponse, error)
	GetStream(ctx context.Context, in *GetStreamRequest, opts ...grpc.CallOption) (*StreamInfo, error)
}

type streamManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamManagerClient(cc grpc.ClientConnInterface) StreamManagerClient {
	return &streamManagerClient{cc}
}

func (c *streamManagerClient) StartStream(ctx context.Context, in *StartStreamRequest, opts ...grpc.CallOption) (*StartStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartStreamResponse)
	err := c.cc.Invoke(ctx, StreamManager_StartStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamManagerClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, StreamManager_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamManagerClient) StopStream(ctx context.Context, in *StopStreamRequest, opts ...grpc.CallOption) (*StopStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopStreamResponse)
	err := c.cc.Invoke(ctx, StreamManager_StopStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamManagerClient) UpdateSessionMetrics(ctx context.Context, in *UpdateSessionMetricsRequest, opts ...grpc.CallOption) (*UpdateSessionMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSessionMetricsResponse)
	err := c.cc.Invoke(ctx, StreamManager_UpdateSessionMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamManagerClient) UpdateStreamMetadata(ctx context.Context, in *UpdateMetadataRequest, opts ...grpc.CallOption) (*UpdateMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMetadataResponse)
	err := c.cc.Invoke(ctx, StreamManager_UpdateStreamMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamManagerClient) GetLiveStreams(ctx context.Context, in *GetLiveStreamsRequest, opts ...grpc.CallOption) (*GetLiveStreamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLiveStreamsResponse)
	err := c.cc.Invoke(ctx, StreamManager_GetLiveStreams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamManagerClient) GetStream(ctx context.Context, in *GetStreamRequest, opts ...grpc.CallOption) (*StreamInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StreamInfo)
	err := c.cc.Invoke(ctx, StreamManager_GetStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamManagerServer is the server API for StreamManager service.
// All implementations must embed UnimplementedStreamManagerServer
// for forward compatibility.
type StreamManagerServer interface {
	// --- Lifecycle (Ingest/Processing) ---
	StartStream(context.Context, *StartStreamRequest) (*StartStreamResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	StopStream(context.Context, *StopStreamRequest) (*StopStreamResponse, error)
	// Allows Ingest/Processing to update resolution/bitrate mid-stream
	UpdateSessionMetrics(context.Context, *UpdateSessionMetricsRequest) (*UpdateSessionMetricsResponse, error)
	// --- User Actions ---
	UpdateStreamMetadata(context.Context, *UpdateMetadataRequest) (*UpdateMetadataResponse, error)
	GetLiveStreams(context.Context, *GetLiveStreamsRequest) (*GetLiveStreamsResponse, error)
	GetStream(context.Context, *GetStreamRequest) (*StreamInfo, error)
	mustEmbedUnimplementedStreamManagerServer()
}

// UnimplementedStreamManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamManagerServer struct{}

func (UnimplementedStreamManagerServer) StartStream(context.Context, *StartStreamRequest) (*StartStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartStream not implemented")
}
func (UnimplementedStreamManagerServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedStreamManagerServer) StopStream(context.Context, *StopStreamRequest) (*StopStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopStream not implemented")
}
func (UnimplementedStreamManagerServer) UpdateSessionMetrics(context.Context, *UpdateSessionMetricsRequest) (*UpdateSessionMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSessionMetrics not implemented")
}
func (UnimplementedStreamManagerServer) UpdateStreamMetadata(context.Context, *UpdateMetadataRequest) (*UpdateMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStreamMetadata not implemented")
}
func (UnimplementedStreamManagerServer) GetLiveStreams(context.Context, *GetLiveStreamsRequest) (*GetLiveStreamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLiveStreams not implemented")
}
func (UnimplementedStreamManagerServer) GetStream(context.Context, *GetStreamRequest) (*StreamInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStream not implemented")
}
func (UnimplementedStreamManagerServer) mustEmbedUnimplementedStreamManagerServer() {}
func (UnimplementedStreamManagerServer) testEmbeddedByValue()                       {}

// UnsafeStreamManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamManagerServer will
// result in compilation errors.
type UnsafeStreamManagerServer interface {
	mustEmbedUnimplementedStreamManagerServer()
}

func RegisterStreamManagerServer(s grpc.ServiceRegistrar, srv StreamManagerServer) {
	// If the following call panics, it indicates UnimplementedStreamManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StreamManager_ServiceDesc, srv)
}

func _StreamManager_StartStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamManagerServer).StartStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamManager_StartStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamManagerServer).StartStream(ctx, req.(*StartStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamManager_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamManagerServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamManager_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamManagerServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamManager_StopStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamManagerServer).StopStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamManager_StopStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamManagerServer).StopStream(ctx, req.(*StopStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamManager_UpdateSessionMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSessionMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamManagerServer).UpdateSessionMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamManager_UpdateSessionMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamManagerServer).UpdateSessionMetrics(ctx, req.(*UpdateSessionMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamManager_UpdateStreamMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamManagerServer).UpdateStreamMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamManager_UpdateStreamMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamManagerServer).UpdateStreamMetadata(ctx, req.(*UpdateMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamManager_GetLiveStreams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLiveStreamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamManagerServer).GetLiveStreams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamManager_GetLiveStreams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamManagerServer).GetLiveStreams(ctx, req.(*GetLiveStreamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamManager_GetStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamManagerServer).GetStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamManager_GetStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamManagerServer).GetStream(ctx, req.(*GetStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StreamManager_ServiceDesc is the grpc.ServiceDesc for StreamManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stream_service.StreamManager",
	HandlerType: (*StreamManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartStream",
			Handler:    _StreamManager_StartStream_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _StreamManager_Heartbeat_Handler,
		},
		{
			MethodName: "StopStream",
			Handler:    _StreamManager_StopStream_Handler,
		},
		{
			MethodName: "UpdateSessionMetrics",
			Handler:    _StreamManager_UpdateSessionMetrics_Handler,
		},
		{
			MethodName: "UpdateStreamMetadata",
			Handler:    _StreamManager_UpdateStreamMetadata_Handler,
		},
		{
			MethodName: "GetLiveStreams",
			Handler:    _StreamManager_GetLiveStreams_Handler,
		},
		{
			MethodName: "GetStream",
			Handler:    _StreamManager_GetStream_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stream_service.proto",
}
