// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: stream_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamStatus int32

const (
	StreamStatus_OFFLINE  StreamStatus = 0
	StreamStatus_LIVE     StreamStatus = 1
	StreamStatus_COMPLETE StreamStatus = 2
	StreamStatus_ERROR    StreamStatus = 3
)

// Enum value maps for StreamStatus.
var (
	StreamStatus_name = map[int32]string{
		0: "OFFLINE",
		1: "LIVE",
		2: "COMPLETE",
		3: "ERROR",
	}
	StreamStatus_value = map[string]int32{
		"OFFLINE":  0,
		"LIVE":     1,
		"COMPLETE": 2,
		"ERROR":    3,
	}
)

func (x StreamStatus) Enum() *StreamStatus {
	p := new(StreamStatus)
	*p = x
	return p
}

func (x StreamStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_stream_service_proto_enumTypes[0].Descriptor()
}

func (StreamStatus) Type() protoreflect.EnumType {
	return &file_stream_service_proto_enumTypes[0]
}

func (x StreamStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamStatus.Descriptor instead.
func (StreamStatus) EnumDescriptor() ([]byte, []int) {
	return file_stream_service_proto_rawDescGZIP(), []int{0}
}

type StartStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamKey     string                 `protobuf:"bytes,1,opt,name=stream_key,json=streamKey,proto3" json:"stream_key,omitempty"`
	Resolution    string                 `protobuf:"bytes,2,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Bitrate       int32                  `protobuf:"varint,3,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	Codec         string                 `protobuf:"bytes,4,opt,name=codec,proto3" json:"codec,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartStreamRequest) Reset() {
	*x = StartStreamRequest{}
	mi := &file_stream_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartStreamRequest) ProtoMessage() {}

func (x *StartStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartStreamRequest.ProtoReflect.Descriptor instead.
func (*StartStreamRequest) Descriptor() ([]byte, []int) {
	return file_stream_service_proto_rawDescGZIP(), []int{0}
}

func (x *StartStreamRequest) GetStreamKey() string {
	if x != nil {
		return x.StreamKey
	}
	return ""
}

func (x *StartStreamRequest) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *StartStreamRequest) GetBitrate() int32 {
	if x != nil {
		return x.Bitrate
	}
	return 0
}

func (x *StartStreamRequest) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *StartStreamRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type StartStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ChannelId     int32                  `protobuf:"varint,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartStreamResponse) Reset() {
	*x = StartStreamResponse{}
	mi := &file_stream_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartStreamResponse) ProtoMessage() {}

func (x *StartStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartStreamResponse.ProtoReflect.Descriptor instead.
func (*StartStreamResponse) Descriptor() ([]byte, []int) {
	return file_stream_service_proto_rawDescGZIP(), []int{1}
}

func (x *StartStreamResponse) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *StartStreamResponse) GetChannelId() int32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

type HeartbeatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CurrentViewers int32                  `protobuf:"varint,2,opt,name=current_viewers,json=currentViewers,proto3" json:"current_viewers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_stream_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_stream_service_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *HeartbeatRequest) GetCurrentViewers() int32 {
	if x != nil {
		return x.CurrentViewers
	}
	return 0
}

type HeartbeatResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ShouldContinue bool                   `protobuf:"varint,1,opt,name=should_continue,json=shouldContinue,proto3" json:"should_continue,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_stream_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_stream_service_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetShouldContinue() bool {
	if x != nil {
		return x.ShouldContinue
	}
	return false
}

type UpdateSessionMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Resolution    string                 `protobuf:"bytes,2,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Bitrate       int32                  `protobuf:"varint,3,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionMetricsRequest) Reset() {
	*x = UpdateSessionMetricsRequest{}
	mi := &file_stream_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionMetricsRequest) ProtoMessage() {}

func (x *UpdateSessionMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionMetricsRequest.ProtoReflect.Descriptor instead.
func (*UpdateSessionMetricsRequest) Descriptor() ([]byte, []int) {
	return file_stream_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSessionMetricsRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *UpdateSessionMetricsRequest) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *UpdateSessionMetricsRequest) GetBitrate() int32 {
	if x != nil {
		return x.Bitrate
	}
	return 0
}

type UpdateSessionMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionMetricsResponse) Reset() {
	*x = UpdateSessionMetricsResponse{}
	mi := &file_stream_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionMetricsResponse) ProtoMessage() {}

func (x *UpdateSessionMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionMetricsResponse.ProtoReflect.Descriptor instead.
func (*UpdateSessionMetricsResponse) Descriptor() ([]byte, []int) {
	return file_stream_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateSessionMetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StopStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopStreamRequest) Reset() {
	*x = StopStreamRequest{}
	mi := &file_stream_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopStreamRequest) ProtoMessage() {}

func (x *StopStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopStreamRequest.ProtoReflect.Descriptor instead.
func (*StopStreamRequest) Descriptor() ([]byte, []int) {
	return file_stream_service_proto_rawDescGZIP(), []int{6}
}

func (x *StopStreamRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

type StopStreamResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DurationSeconds uint32                 `protobuf:"varint,1,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StopStreamResponse) Reset() {
	*x = StopStreamResponse{}
	mi := &file_stream_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopStreamResponse) ProtoMessage() {}

func (x *StopStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopStreamResponse.ProtoReflect.Descriptor instead.
func (*StopStreamResponse) Descriptor() ([]byte, []int) {
	return file_stream_service_proto_rawDescGZIP(), []int{7}
}

func (x *StopStreamResponse) GetDurationSeconds() uint32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

type UpdateMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     int32                  `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetadataRequest) Reset() {
	*x = UpdateMetadataRequest{}
	mi := &file_stream_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetadataRequest) ProtoMessage() {}

func (x *UpdateMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetadataRequest.ProtoReflect.Descriptor instead.
func (*UpdateMetadataRequest) Descriptor() ([]byte, []int) {
	return file_stream_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateMetadataRequest) GetChannelId() int32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *UpdateMetadataRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateMetadataRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetadataResponse) Reset() {
	*x = UpdateMetadataResponse{}
	mi := &file_stream_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetadataResponse) ProtoMessage() {}

func (x *UpdateMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetadataResponse.ProtoReflect.Descriptor instead.
func (*UpdateMetadataResponse) Descriptor() ([]byte, []int) {
	return file_stream_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateMetadataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetLiveStreamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLiveStreamsRequest) Reset() {
	*x = GetLiveStreamsRequest{}
	mi := &file_stream_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLiveStreamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLiveStreamsRequest) ProtoMessage() {}

func (x *GetLiveStreamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLiveStreamsRequest.ProtoReflect.Descriptor instead.
func (*GetLiveStreamsRequest) Descriptor() ([]byte, []int) {
	return file_stream_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetLiveStreamsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetLiveStreamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Streams       []*StreamInfo          `protobuf:"bytes,1,rep,name=streams,proto3" json:"streams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLiveStreamsResponse) Reset() {
	*x = GetLiveStreamsResponse{}
	mi := &file_stream_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLiveStreamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLiveStreamsResponse) ProtoMessage() {}

func (x *GetLiveStreamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLiveStreamsResponse.ProtoReflect.Descriptor instead.
func (*GetLiveStreamsResponse) Descriptor() ([]byte, []int) {
	return file_stream_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetLiveStreamsResponse) GetStreams() []*StreamInfo {
	if x != nil {
		return x.Streams
	}
	return nil
}

type GetStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Can be a numeric string ("123") or a username ("alice")
	Identifier    string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamRequest) Reset() {
	*x = GetStreamRequest{}
	mi := &file_stream_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamRequest) ProtoMessage() {}

func (x *GetStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamRequest.ProtoReflect.Descriptor instead.
func (*GetStreamRequest) Descriptor() ([]byte, []int) {
	return file_stream_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetStreamRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

type StreamInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChannelId       int32                  `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	SessionId       int64                  `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Username        string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Title           string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	ViewerCount     int32                  `protobuf:"varint,6,opt,name=viewer_count,json=viewerCount,proto3" json:"viewer_count,omitempty"`
	Resolution      string                 `protobuf:"bytes,7,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Status          StreamStatus           `protobuf:"varint,8,opt,name=status,proto3,enum=stream_service.StreamStatus" json:"status,omitempty"` // Good to include for frontend logic
	ProfileImageUrl string                 `protobuf:"bytes,9,opt,name=profile_image_url,json=profileImageUrl,proto3" json:"profile_image_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamInfo) Reset() {
	*x = StreamInfo{}
	mi := &file_stream_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInfo) ProtoMessage() {}

func (x *StreamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_stream_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInfo.ProtoReflect.Descriptor instead.
func (*StreamInfo) Descriptor() ([]byte, []int) {
	return file_stream_service_proto_rawDescGZIP(), []int{13}
}

func (x *StreamInfo) GetChannelId() int32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *StreamInfo) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *StreamInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *StreamInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *StreamInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StreamInfo) GetViewerCount() int32 {
	if x != nil {
		return x.ViewerCount
	}
	return 0
}

func (x *StreamInfo) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *StreamInfo) GetStatus() StreamStatus {
	if x != nil {
		return x.Status
	}
	return StreamStatus_OFFLINE
}

func (x *StreamInfo) GetProfileImageUrl() string {
	if x != nil {
		return x.ProfileImageUrl
	}
	return ""
}

var File_stream_service_proto protoreflect.FileDescriptor

const file_stream_service_proto_rawDesc = "" +
	"\n" +
	"\x14stream_service.proto\x12\x0estream_service\"\x9f\x01\n" +
	"\x12StartStreamRequest\x12\x1d\n" +
	"\n" +
	"stream_key\x18\x01 \x01(\tR\tstreamKey\x12\x1e\n" +
	"\n" +
	"resolution\x18\x02 \x01(\tR\n" +
	"resolution\x12\x18\n" +
	"\abitrate\x18\x03 \x01(\x05R\abitrate\x12\x14\n" +
	"\x05codec\x18\x04 \x01(\tR\x05codec\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\"S\n" +
	"\x13StartStreamResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\x05R\tchannelId\"Z\n" +
	"\x10HeartbeatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\x12'\n" +
	"\x0fcurrent_viewers\x18\x02 \x01(\x05R\x0ecurrentViewers\"<\n" +
	"\x11HeartbeatResponse\x12'\n" +
	"\x0fshould_continue\x18\x01 \x01(\bR\x0eshouldContinue\"v\n" +
	"\x1bUpdateSessionMetricsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\x12\x1e\n" +
	"\n" +
	"resolution\x18\x02 \x01(\tR\n" +
	"resolution\x12\x18\n" +
	"\abitrate\x18\x03 \x01(\x05R\abitrate\"8\n" +
	"\x1cUpdateSessionMetricsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"2\n" +
	"\x11StopStreamRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\"?\n" +
	"\x12StopStreamResponse\x12)\n" +
	"\x10duration_seconds\x18\x01 \x01(\rR\x0fdurationSeconds\"n\n" +
	"\x15UpdateMetadataRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x05R\tchannelId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"2\n" +
	"\x16UpdateMetadataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"-\n" +
	"\x15GetLiveStreamsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"N\n" +
	"\x16GetLiveStreamsResponse\x124\n" +
	"\astreams\x18\x01 \x03(\v2\x1a.stream_service.StreamInfoR\astreams\"2\n" +
	"\x10GetStreamRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\"\xc3\x02\n" +
	"\n" +
	"StreamInfo\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x05R\tchannelId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\x03R\tsessionId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12!\n" +
	"\fviewer_count\x18\x06 \x01(\x05R\vviewerCount\x12\x1e\n" +
	"\n" +
	"resolution\x18\a \x01(\tR\n" +
	"resolution\x124\n" +
	"\x06status\x18\b \x01(\x0e2\x1c.stream_service.StreamStatusR\x06status\x12*\n" +
	"\x11profile_image_url\x18\t \x01(\tR\x0fprofileImageUrl*>\n" +
	"\fStreamStatus\x12\v\n" +
	"\aOFFLINE\x10\x00\x12\b\n" +
	"\x04LIVE\x10\x01\x12\f\n" +
	"\bCOMPLETE\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x032\x94\x05\n" +
	"\rStreamManager\x12V\n" +
	"\vStartStream\x12\".stream_service.StartStreamRequest\x1a#.stream_service.StartStreamResponse\x12P\n" +
	"\tHeartbeat\x12 .stream_service.HeartbeatRequest\x1a!.stream_service.HeartbeatResponse\x12S\n" +
	"\n" +
	"StopStream\x12!.stream_service.StopStreamRequest\x1a\".stream_service.StopStreamResponse\x12q\n" +
	"\x14UpdateSessionMetrics\x12+.stream_service.UpdateSessionMetricsRequest\x1a,.stream_service.UpdateSessionMetricsResponse\x12e\n" +
	"\x14UpdateStreamMetadata\x12%.stream_service.UpdateMetadataRequest\x1a&.stream_service.UpdateMetadataResponse\x12_\n" +
	"\x0eGetLiveStreams\x12%.stream_service.GetLiveStreamsRequest\x1a&.stream_service.GetLiveStreamsResponse\x12I\n" +
	"\tGetStream\x12 .stream_service.GetStreamRequest\x1a\x1a.stream_service.StreamInfoB\x06Z\x04./pbb\x06proto3"

var (
	file_stream_service_proto_rawDescOnce sync.Once
	file_stream_service_proto_rawDescData []byte
)

func file_stream_service_proto_rawDescGZIP() []byte {
	file_stream_service_proto_rawDescOnce.Do(func() {
		file_stream_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stream_service_proto_rawDesc), len(file_stream_service_proto_rawDesc)))
	})
	return file_stream_service_proto_rawDescData
}

var file_stream_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_stream_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_stream_service_proto_goTypes = []any{
	(StreamStatus)(0),                    // 0: stream_service.StreamStatus
	(*StartStreamRequest)(nil),           // 1: stream_service.StartStreamRequest
	(*StartStreamResponse)(nil),          // 2: stream_service.StartStreamResponse
	(*HeartbeatRequest)(nil),             // 3: stream_service.HeartbeatRequest
	(*HeartbeatResponse)(nil),            // 4: stream_service.HeartbeatResponse
	(*UpdateSessionMetricsRequest)(nil),  // 5: stream_service.UpdateSessionMetricsRequest
	(*UpdateSessionMetricsResponse)(nil), // 6: stream_service.UpdateSessionMetricsResponse
	(*StopStreamRequest)(nil),            // 7: stream_service.StopStreamRequest
	(*StopStreamResponse)(nil),           // 8: stream_service.StopStreamResponse
	(*UpdateMetadataRequest)(nil),        // 9: stream_service.UpdateMetadataRequest
	(*UpdateMetadataResponse)(nil),       // 10: stream_service.UpdateMetadataResponse
	(*GetLiveStreamsRequest)(nil),        // 11: stream_service.GetLiveStreamsRequest
	(*GetLiveStreamsResponse)(nil),       // 12: stream_service.GetLiveStreamsResponse
	(*GetStreamRequest)(nil),             // 13: stream_service.GetStreamRequest
	(*StreamInfo)(nil),                   // 14: stream_service.StreamInfo
}
var file_stream_service_proto_depIdxs = []int32{
	14, // 0: stream_service.GetLiveStreamsResponse.streams:type_name -> stream_service.StreamInfo
	0,  // 1: stream_service.StreamInfo.status:type_name -> stream_service.StreamStatus
	1,  // 2: stream_service.StreamManager.StartStream:input_type -> stream_service.StartStreamRequest
	3,  // 3: stream_service.StreamManager.Heartbeat:input_type -> stream_service.HeartbeatRequest
	7,  // 4: stream_service.StreamManager.StopStream:input_type -> stream_service.StopStreamRequest
	5,  // 5: stream_service.StreamManager.UpdateSessionMetrics:input_type -> stream_service.UpdateSessionMetricsRequest
	9,  // 6: stream_service.StreamManager.UpdateStreamMetadata:input_type -> stream_service.UpdateMetadataRequest
	11, // 7: stream_service.StreamManager.GetLiveStreams:input_type -> stream_service.GetLiveStreamsRequest
	13, // 8: stream_service.StreamManager.GetStream:input_type -> stream_service.GetStreamRequest
	2,  // 9: stream_service.StreamManager.StartStream:output_type -> stream_service.StartStreamResponse
	4,  // 10: stream_service.StreamManager.Heartbeat:output_type -> stream_service.HeartbeatResponse
	8,  // 11: stream_service.StreamManager.StopStream:output_type -> stream_service.StopStreamResponse
	6,  // 12: stream_service.StreamManager.UpdateSessionMetrics:output_type -> stream_service.UpdateSessionMetricsResponse
	10, // 13: stream_service.StreamManager.UpdateStreamMetadata:output_type -> stream_service.UpdateMetadataResponse
	12, // 14: stream_service.StreamManager.GetLiveStreams:output_type -> stream_service.GetLiveStreamsResponse
	14, // 15: stream_service.StreamManager.GetStream:output_type -> stream_service.StreamInfo
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_stream_service_proto_init() }
func file_stream_service_proto_init() {
	if File_stream_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stream_service_proto_rawDesc), len(file_stream_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stream_service_proto_goTypes,
		DependencyIndexes: file_stream_service_proto_depIdxs,
		EnumInfos:         file_stream_service_proto_enumTypes,
		MessageInfos:      file_stream_service_proto_msgTypes,
	}.Build()
	File_stream_service_proto = out.File
	file_stream_service_proto_goTypes = nil
	file_stream_service_proto_depIdxs = nil
}
