// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: internal/proto/user/user.proto

package user

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserStatus int32

const (
	UserStatus_ACTIVE    UserStatus = 0
	UserStatus_SUSPENDED UserStatus = 1
	UserStatus_BANNED    UserStatus = 2
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "ACTIVE",
		1: "SUSPENDED",
		2: "BANNED",
	}
	UserStatus_value = map[string]int32{
		"ACTIVE":    0,
		"SUSPENDED": 1,
		"BANNED":    2,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_user_user_proto_enumTypes[0].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_internal_proto_user_user_proto_enumTypes[0]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_user_user_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Roles         []string               `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	Status        UserStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=user.UserStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IsVerified    bool                   `protobuf:"varint,7,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"` // <--- Add this
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_internal_proto_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *User) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_ACTIVE
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

type UserInternal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *User                  `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInternal) Reset() {
	*x = UserInternal{}
	mi := &file_internal_proto_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInternal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInternal) ProtoMessage() {}

func (x *UserInternal) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInternal.ProtoReflect.Descriptor instead.
func (*UserInternal) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserInternal) GetProfile() *User {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *UserInternal) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Roles         []string               `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_internal_proto_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type GetUserByUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByUsernameRequest) Reset() {
	*x = GetUserByUsernameRequest{}
	mi := &file_internal_proto_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByUsernameRequest) ProtoMessage() {}

func (x *GetUserByUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByUsernameRequest.ProtoReflect.Descriptor instead.
func (*GetUserByUsernameRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserByUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetUserByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIDRequest) Reset() {
	*x = GetUserByIDRequest{}
	mi := &file_internal_proto_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIDRequest) ProtoMessage() {}

func (x *GetUserByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIDRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserByIDRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UpdateUserPasswordRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NewPasswordHash string                 `protobuf:"bytes,2,opt,name=new_password_hash,json=newPasswordHash,proto3" json:"new_password_hash,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateUserPasswordRequest) Reset() {
	*x = UpdateUserPasswordRequest{}
	mi := &file_internal_proto_user_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPasswordRequest) ProtoMessage() {}

func (x *UpdateUserPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserPasswordRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserPasswordRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserPasswordRequest) GetNewPasswordHash() string {
	if x != nil {
		return x.NewPasswordHash
	}
	return ""
}

type UpdateUserStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        UserStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=user.UserStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserStatusRequest) Reset() {
	*x = UpdateUserStatusRequest{}
	mi := &file_internal_proto_user_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserStatusRequest) ProtoMessage() {}

func (x *UpdateUserStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserStatusRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserStatusRequest) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_ACTIVE
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_internal_proto_user_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_user_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AddUserRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserRoleRequest) Reset() {
	*x = AddUserRoleRequest{}
	mi := &file_internal_proto_user_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserRoleRequest) ProtoMessage() {}

func (x *AddUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserRoleRequest.ProtoReflect.Descriptor instead.
func (*AddUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_user_proto_rawDescGZIP(), []int{8}
}

func (x *AddUserRoleRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddUserRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type RemoveUserRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserRoleRequest) Reset() {
	*x = RemoveUserRoleRequest{}
	mi := &file_internal_proto_user_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserRoleRequest) ProtoMessage() {}

func (x *RemoveUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserRoleRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_user_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveUserRoleRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RemoveUserRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type VerifyUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyUserRequest) Reset() {
	*x = VerifyUserRequest{}
	mi := &file_internal_proto_user_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyUserRequest) ProtoMessage() {}

func (x *VerifyUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyUserRequest.ProtoReflect.Descriptor instead.
func (*VerifyUserRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_user_proto_rawDescGZIP(), []int{10}
}

func (x *VerifyUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_internal_proto_user_user_proto protoreflect.FileDescriptor

const file_internal_proto_user_user_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/proto/user/user.proto\x12\x04user\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xed\x01\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\x12(\n" +
	"\x06status\x18\x05 \x01(\x0e2\x10.user.UserStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1f\n" +
	"\vis_verified\x18\a \x01(\bR\n" +
	"isVerified\"Y\n" +
	"\fUserInternal\x12$\n" +
	"\aprofile\x18\x01 \x01(\v2\n" +
	".user.UserR\aprofile\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\tR\fpasswordHash\"\x80\x01\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\tR\fpasswordHash\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\"6\n" +
	"\x18GetUserByUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"-\n" +
	"\x12GetUserByIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"`\n" +
	"\x19UpdateUserPasswordRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12*\n" +
	"\x11new_password_hash\x18\x02 \x01(\tR\x0fnewPasswordHash\"\\\n" +
	"\x17UpdateUserStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12(\n" +
	"\x06status\x18\x02 \x01(\x0e2\x10.user.UserStatusR\x06status\",\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"A\n" +
	"\x12AddUserRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"D\n" +
	"\x15RemoveUserRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\",\n" +
	"\x11VerifyUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId*3\n" +
	"\n" +
	"UserStatus\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x00\x12\r\n" +
	"\tSUSPENDED\x10\x01\x12\n" +
	"\n" +
	"\x06BANNED\x10\x022\xe6\x04\n" +
	"\vUserService\x121\n" +
	"\n" +
	"CreateUser\x12\x17.user.CreateUserRequest\x1a\n" +
	".user.User\x12;\n" +
	"\vGetUserByID\x12\x18.user.GetUserByIDRequest\x1a\x12.user.UserInternal\x12G\n" +
	"\x11GetUserByUsername\x12\x1e.user.GetUserByUsernameRequest\x1a\x12.user.UserInternal\x12M\n" +
	"\x12UpdateUserPassword\x12\x1f.user.UpdateUserPasswordRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\x10UpdateUserStatus\x12\x1d.user.UpdateUserStatusRequest\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\n" +
	"DeleteUser\x12\x17.user.DeleteUserRequest\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\vAddUserRole\x12\x18.user.AddUserRoleRequest\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\x0eRemoveUserRole\x12\x1b.user.RemoveUserRoleRequest\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\n" +
	"VerifyUser\x12\x17.user.VerifyUserRequest\x1a\x16.google.protobuf.EmptyB9Z7github.com/clementus360/go_database/internal/proto/userb\x06proto3"

var (
	file_internal_proto_user_user_proto_rawDescOnce sync.Once
	file_internal_proto_user_user_proto_rawDescData []byte
)

func file_internal_proto_user_user_proto_rawDescGZIP() []byte {
	file_internal_proto_user_user_proto_rawDescOnce.Do(func() {
		file_internal_proto_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_user_user_proto_rawDesc), len(file_internal_proto_user_user_proto_rawDesc)))
	})
	return file_internal_proto_user_user_proto_rawDescData
}

var file_internal_proto_user_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_proto_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_proto_user_user_proto_goTypes = []any{
	(UserStatus)(0),                   // 0: user.UserStatus
	(*User)(nil),                      // 1: user.User
	(*UserInternal)(nil),              // 2: user.UserInternal
	(*CreateUserRequest)(nil),         // 3: user.CreateUserRequest
	(*GetUserByUsernameRequest)(nil),  // 4: user.GetUserByUsernameRequest
	(*GetUserByIDRequest)(nil),        // 5: user.GetUserByIDRequest
	(*UpdateUserPasswordRequest)(nil), // 6: user.UpdateUserPasswordRequest
	(*UpdateUserStatusRequest)(nil),   // 7: user.UpdateUserStatusRequest
	(*DeleteUserRequest)(nil),         // 8: user.DeleteUserRequest
	(*AddUserRoleRequest)(nil),        // 9: user.AddUserRoleRequest
	(*RemoveUserRoleRequest)(nil),     // 10: user.RemoveUserRoleRequest
	(*VerifyUserRequest)(nil),         // 11: user.VerifyUserRequest
	(*timestamppb.Timestamp)(nil),     // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 13: google.protobuf.Empty
}
var file_internal_proto_user_user_proto_depIdxs = []int32{
	0,  // 0: user.User.status:type_name -> user.UserStatus
	12, // 1: user.User.created_at:type_name -> google.protobuf.Timestamp
	1,  // 2: user.UserInternal.profile:type_name -> user.User
	0,  // 3: user.UpdateUserStatusRequest.status:type_name -> user.UserStatus
	3,  // 4: user.UserService.CreateUser:input_type -> user.CreateUserRequest
	5,  // 5: user.UserService.GetUserByID:input_type -> user.GetUserByIDRequest
	4,  // 6: user.UserService.GetUserByUsername:input_type -> user.GetUserByUsernameRequest
	6,  // 7: user.UserService.UpdateUserPassword:input_type -> user.UpdateUserPasswordRequest
	7,  // 8: user.UserService.UpdateUserStatus:input_type -> user.UpdateUserStatusRequest
	8,  // 9: user.UserService.DeleteUser:input_type -> user.DeleteUserRequest
	9,  // 10: user.UserService.AddUserRole:input_type -> user.AddUserRoleRequest
	10, // 11: user.UserService.RemoveUserRole:input_type -> user.RemoveUserRoleRequest
	11, // 12: user.UserService.VerifyUser:input_type -> user.VerifyUserRequest
	1,  // 13: user.UserService.CreateUser:output_type -> user.User
	2,  // 14: user.UserService.GetUserByID:output_type -> user.UserInternal
	2,  // 15: user.UserService.GetUserByUsername:output_type -> user.UserInternal
	13, // 16: user.UserService.UpdateUserPassword:output_type -> google.protobuf.Empty
	13, // 17: user.UserService.UpdateUserStatus:output_type -> google.protobuf.Empty
	13, // 18: user.UserService.DeleteUser:output_type -> google.protobuf.Empty
	13, // 19: user.UserService.AddUserRole:output_type -> google.protobuf.Empty
	13, // 20: user.UserService.RemoveUserRole:output_type -> google.protobuf.Empty
	13, // 21: user.UserService.VerifyUser:output_type -> google.protobuf.Empty
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_internal_proto_user_user_proto_init() }
func file_internal_proto_user_user_proto_init() {
	if File_internal_proto_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_user_user_proto_rawDesc), len(file_internal_proto_user_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_user_user_proto_goTypes,
		DependencyIndexes: file_internal_proto_user_user_proto_depIdxs,
		EnumInfos:         file_internal_proto_user_user_proto_enumTypes,
		MessageInfos:      file_internal_proto_user_user_proto_msgTypes,
	}.Build()
	File_internal_proto_user_user_proto = out.File
	file_internal_proto_user_user_proto_goTypes = nil
	file_internal_proto_user_user_proto_depIdxs = nil
}
