// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: stream.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamStatus int32

const (
	StreamStatus_OFFLINE  StreamStatus = 0
	StreamStatus_LIVE     StreamStatus = 1
	StreamStatus_COMPLETE StreamStatus = 2
	StreamStatus_ERROR    StreamStatus = 3
)

// Enum value maps for StreamStatus.
var (
	StreamStatus_name = map[int32]string{
		0: "OFFLINE",
		1: "LIVE",
		2: "COMPLETE",
		3: "ERROR",
	}
	StreamStatus_value = map[string]int32{
		"OFFLINE":  0,
		"LIVE":     1,
		"COMPLETE": 2,
		"ERROR":    3,
	}
)

func (x StreamStatus) Enum() *StreamStatus {
	p := new(StreamStatus)
	*p = x
	return p
}

func (x StreamStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_stream_proto_enumTypes[0].Descriptor()
}

func (StreamStatus) Type() protoreflect.EnumType {
	return &file_stream_proto_enumTypes[0]
}

func (x StreamStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamStatus.Descriptor instead.
func (StreamStatus) EnumDescriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{0}
}

type ChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StreamKey     string                 `protobuf:"bytes,3,opt,name=stream_key,json=streamKey,proto3" json:"stream_key,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	IsLive        bool                   `protobuf:"varint,6,opt,name=is_live,json=isLive,proto3" json:"is_live,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelResponse) Reset() {
	*x = ChannelResponse{}
	mi := &file_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelResponse) ProtoMessage() {}

func (x *ChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelResponse.ProtoReflect.Descriptor instead.
func (*ChannelResponse) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{0}
}

func (x *ChannelResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChannelResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChannelResponse) GetStreamKey() string {
	if x != nil {
		return x.StreamKey
	}
	return ""
}

func (x *ChannelResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ChannelResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ChannelResponse) GetIsLive() bool {
	if x != nil {
		return x.IsLive
	}
	return false
}

func (x *ChannelResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SessionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ChannelId       int32                  `protobuf:"varint,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Status          StreamStatus           `protobuf:"varint,3,opt,name=status,proto3,enum=stream.StreamStatus" json:"status,omitempty"`
	Resolution      string                 `protobuf:"bytes,4,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Bitrate         int32                  `protobuf:"varint,5,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	Codec           string                 `protobuf:"bytes,6,opt,name=codec,proto3" json:"codec,omitempty"`
	ViewCount       int32                  `protobuf:"varint,7,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	StartTime       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	LastHeartbeatAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_heartbeat_at,json=lastHeartbeatAt,proto3" json:"last_heartbeat_at,omitempty"` // NEW
	Category        string                 `protobuf:"bytes,11,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SessionResponse) Reset() {
	*x = SessionResponse{}
	mi := &file_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResponse) ProtoMessage() {}

func (x *SessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResponse.ProtoReflect.Descriptor instead.
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{1}
}

func (x *SessionResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SessionResponse) GetChannelId() int32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *SessionResponse) GetStatus() StreamStatus {
	if x != nil {
		return x.Status
	}
	return StreamStatus_OFFLINE
}

func (x *SessionResponse) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *SessionResponse) GetBitrate() int32 {
	if x != nil {
		return x.Bitrate
	}
	return 0
}

func (x *SessionResponse) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *SessionResponse) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *SessionResponse) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *SessionResponse) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *SessionResponse) GetLastHeartbeatAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeatAt
	}
	return nil
}

func (x *SessionResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type CreateChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StreamKey     string                 `protobuf:"bytes,2,opt,name=stream_key,json=streamKey,proto3" json:"stream_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChannelRequest) Reset() {
	*x = CreateChannelRequest{}
	mi := &file_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelRequest) ProtoMessage() {}

func (x *CreateChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelRequest.ProtoReflect.Descriptor instead.
func (*CreateChannelRequest) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{2}
}

func (x *CreateChannelRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateChannelRequest) GetStreamKey() string {
	if x != nil {
		return x.StreamKey
	}
	return ""
}

type GetChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int32                 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	UserId        *int64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	StreamKey     *string                `protobuf:"bytes,3,opt,name=stream_key,json=streamKey,proto3,oneof" json:"stream_key,omitempty"` // Add this to your existing proto
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelRequest) Reset() {
	*x = GetChannelRequest{}
	mi := &file_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelRequest) ProtoMessage() {}

func (x *GetChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelRequest.ProtoReflect.Descriptor instead.
func (*GetChannelRequest) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{3}
}

func (x *GetChannelRequest) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *GetChannelRequest) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *GetChannelRequest) GetStreamKey() string {
	if x != nil && x.StreamKey != nil {
		return *x.StreamKey
	}
	return ""
}

type UpdateChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	StreamKey     *string                `protobuf:"bytes,4,opt,name=stream_key,json=streamKey,proto3,oneof" json:"stream_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChannelRequest) Reset() {
	*x = UpdateChannelRequest{}
	mi := &file_stream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChannelRequest) ProtoMessage() {}

func (x *UpdateChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChannelRequest.ProtoReflect.Descriptor instead.
func (*UpdateChannelRequest) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateChannelRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateChannelRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateChannelRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateChannelRequest) GetStreamKey() string {
	if x != nil && x.StreamKey != nil {
		return *x.StreamKey
	}
	return ""
}

type DeleteChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChannelRequest) Reset() {
	*x = DeleteChannelRequest{}
	mi := &file_stream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChannelRequest) ProtoMessage() {}

func (x *DeleteChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChannelRequest.ProtoReflect.Descriptor instead.
func (*DeleteChannelRequest) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteChannelRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     int32                  `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Resolution    string                 `protobuf:"bytes,2,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Bitrate       int32                  `protobuf:"varint,3,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	Codec         string                 `protobuf:"bytes,4,opt,name=codec,proto3" json:"codec,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_stream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{6}
}

func (x *CreateSessionRequest) GetChannelId() int32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *CreateSessionRequest) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *CreateSessionRequest) GetBitrate() int32 {
	if x != nil {
		return x.Bitrate
	}
	return 0
}

func (x *CreateSessionRequest) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *CreateSessionRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_stream_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{7}
}

func (x *GetSessionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Resolution    *string                `protobuf:"bytes,2,opt,name=resolution,proto3,oneof" json:"resolution,omitempty"`
	Bitrate       *int32                 `protobuf:"varint,3,opt,name=bitrate,proto3,oneof" json:"bitrate,omitempty"`
	ViewCount     *int32                 `protobuf:"varint,4,opt,name=view_count,json=viewCount,proto3,oneof" json:"view_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionRequest) Reset() {
	*x = UpdateSessionRequest{}
	mi := &file_stream_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionRequest) ProtoMessage() {}

func (x *UpdateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionRequest.ProtoReflect.Descriptor instead.
func (*UpdateSessionRequest) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateSessionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSessionRequest) GetResolution() string {
	if x != nil && x.Resolution != nil {
		return *x.Resolution
	}
	return ""
}

func (x *UpdateSessionRequest) GetBitrate() int32 {
	if x != nil && x.Bitrate != nil {
		return *x.Bitrate
	}
	return 0
}

func (x *UpdateSessionRequest) GetViewCount() int32 {
	if x != nil && x.ViewCount != nil {
		return *x.ViewCount
	}
	return 0
}

type EndSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionRequest) Reset() {
	*x = EndSessionRequest{}
	mi := &file_stream_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionRequest) ProtoMessage() {}

func (x *EndSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionRequest.ProtoReflect.Descriptor instead.
func (*EndSessionRequest) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{9}
}

func (x *EndSessionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     int32                  `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageNumber    int32                  `protobuf:"varint,3,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_stream_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{10}
}

func (x *ListSessionsRequest) GetChannelId() int32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *ListSessionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSessionsRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionResponse     `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	MetaData      *PaginationMetadata    `protobuf:"bytes,2,opt,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_stream_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{11}
}

func (x *ListSessionsResponse) GetSessions() []*SessionResponse {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListSessionsResponse) GetMetaData() *PaginationMetadata {
	if x != nil {
		return x.MetaData
	}
	return nil
}

type UpdateProcessingStatusRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SessionId          int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status             *StreamStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=stream.StreamStatus,oneof" json:"status,omitempty"`
	ViewCountIncrement *int32                 `protobuf:"varint,3,opt,name=view_count_increment,json=viewCountIncrement,proto3,oneof" json:"view_count_increment,omitempty"`
	CurrentViewCount   *int32                 `protobuf:"varint,4,opt,name=current_view_count,json=currentViewCount,proto3,oneof" json:"current_view_count,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateProcessingStatusRequest) Reset() {
	*x = UpdateProcessingStatusRequest{}
	mi := &file_stream_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProcessingStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProcessingStatusRequest) ProtoMessage() {}

func (x *UpdateProcessingStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProcessingStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateProcessingStatusRequest) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateProcessingStatusRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *UpdateProcessingStatusRequest) GetStatus() StreamStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return StreamStatus_OFFLINE
}

func (x *UpdateProcessingStatusRequest) GetViewCountIncrement() int32 {
	if x != nil && x.ViewCountIncrement != nil {
		return *x.ViewCountIncrement
	}
	return 0
}

func (x *UpdateProcessingStatusRequest) GetCurrentViewCount() int32 {
	if x != nil && x.CurrentViewCount != nil {
		return *x.CurrentViewCount
	}
	return 0
}

type GetStreamKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamKeyRequest) Reset() {
	*x = GetStreamKeyRequest{}
	mi := &file_stream_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamKeyRequest) ProtoMessage() {}

func (x *GetStreamKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamKeyRequest.ProtoReflect.Descriptor instead.
func (*GetStreamKeyRequest) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{13}
}

func (x *GetStreamKeyRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetStreamKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamKey     string                 `protobuf:"bytes,1,opt,name=stream_key,json=streamKey,proto3" json:"stream_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamKeyResponse) Reset() {
	*x = GetStreamKeyResponse{}
	mi := &file_stream_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamKeyResponse) ProtoMessage() {}

func (x *GetStreamKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamKeyResponse.ProtoReflect.Descriptor instead.
func (*GetStreamKeyResponse) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{14}
}

func (x *GetStreamKeyResponse) GetStreamKey() string {
	if x != nil {
		return x.StreamKey
	}
	return ""
}

type ResetStreamKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NewKey        string                 `protobuf:"bytes,2,opt,name=new_key,json=newKey,proto3" json:"new_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetStreamKeyRequest) Reset() {
	*x = ResetStreamKeyRequest{}
	mi := &file_stream_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetStreamKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetStreamKeyRequest) ProtoMessage() {}

func (x *ResetStreamKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetStreamKeyRequest.ProtoReflect.Descriptor instead.
func (*ResetStreamKeyRequest) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{15}
}

func (x *ResetStreamKeyRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ResetStreamKeyRequest) GetNewKey() string {
	if x != nil {
		return x.NewKey
	}
	return ""
}

type GetStaleSessionsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ThresholdSeconds int32                  `protobuf:"varint,1,opt,name=threshold_seconds,json=thresholdSeconds,proto3" json:"threshold_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetStaleSessionsRequest) Reset() {
	*x = GetStaleSessionsRequest{}
	mi := &file_stream_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStaleSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStaleSessionsRequest) ProtoMessage() {}

func (x *GetStaleSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStaleSessionsRequest.ProtoReflect.Descriptor instead.
func (*GetStaleSessionsRequest) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{16}
}

func (x *GetStaleSessionsRequest) GetThresholdSeconds() int32 {
	if x != nil {
		return x.ThresholdSeconds
	}
	return 0
}

type GetStaleSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionIds    []int64                `protobuf:"varint,1,rep,packed,name=session_ids,json=sessionIds,proto3" json:"session_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStaleSessionsResponse) Reset() {
	*x = GetStaleSessionsResponse{}
	mi := &file_stream_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStaleSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStaleSessionsResponse) ProtoMessage() {}

func (x *GetStaleSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStaleSessionsResponse.ProtoReflect.Descriptor instead.
func (*GetStaleSessionsResponse) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{17}
}

func (x *GetStaleSessionsResponse) GetSessionIds() []int64 {
	if x != nil {
		return x.SessionIds
	}
	return nil
}

type UpdateSessionHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionHeartbeatRequest) Reset() {
	*x = UpdateSessionHeartbeatRequest{}
	mi := &file_stream_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionHeartbeatRequest) ProtoMessage() {}

func (x *UpdateSessionHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*UpdateSessionHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateSessionHeartbeatRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

var File_stream_proto protoreflect.FileDescriptor

const file_stream_proto_rawDesc = "" +
	"\n" +
	"\fstream.proto\x12\x06stream\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\fcommon.proto\"\xe5\x01\n" +
	"\x0fChannelResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"stream_key\x18\x03 \x01(\tR\tstreamKey\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x17\n" +
	"\ais_live\x18\x06 \x01(\bR\x06isLive\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb3\x03\n" +
	"\x0fSessionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\x05R\tchannelId\x12,\n" +
	"\x06status\x18\x03 \x01(\x0e2\x14.stream.StreamStatusR\x06status\x12\x1e\n" +
	"\n" +
	"resolution\x18\x04 \x01(\tR\n" +
	"resolution\x12\x18\n" +
	"\abitrate\x18\x05 \x01(\x05R\abitrate\x12\x14\n" +
	"\x05codec\x18\x06 \x01(\tR\x05codec\x12\x1d\n" +
	"\n" +
	"view_count\x18\a \x01(\x05R\tviewCount\x129\n" +
	"\n" +
	"start_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12F\n" +
	"\x11last_heartbeat_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x0flastHeartbeatAt\x12\x1a\n" +
	"\bcategory\x18\v \x01(\tR\bcategory\"N\n" +
	"\x14CreateChannelRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"stream_key\x18\x02 \x01(\tR\tstreamKey\"\x8c\x01\n" +
	"\x11GetChannelRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x05H\x00R\x02id\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\x02 \x01(\x03H\x01R\x06userId\x88\x01\x01\x12\"\n" +
	"\n" +
	"stream_key\x18\x03 \x01(\tH\x02R\tstreamKey\x88\x01\x01B\x05\n" +
	"\x03_idB\n" +
	"\n" +
	"\b_user_idB\r\n" +
	"\v_stream_key\"\xb5\x01\n" +
	"\x14UpdateChannelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\"\n" +
	"\n" +
	"stream_key\x18\x04 \x01(\tH\x02R\tstreamKey\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_stream_key\"&\n" +
	"\x14DeleteChannelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xa1\x01\n" +
	"\x14CreateSessionRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x05R\tchannelId\x12\x1e\n" +
	"\n" +
	"resolution\x18\x02 \x01(\tR\n" +
	"resolution\x12\x18\n" +
	"\abitrate\x18\x03 \x01(\x05R\abitrate\x12\x14\n" +
	"\x05codec\x18\x04 \x01(\tR\x05codec\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\"#\n" +
	"\x11GetSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xb8\x01\n" +
	"\x14UpdateSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\n" +
	"resolution\x18\x02 \x01(\tH\x00R\n" +
	"resolution\x88\x01\x01\x12\x1d\n" +
	"\abitrate\x18\x03 \x01(\x05H\x01R\abitrate\x88\x01\x01\x12\"\n" +
	"\n" +
	"view_count\x18\x04 \x01(\x05H\x02R\tviewCount\x88\x01\x01B\r\n" +
	"\v_resolutionB\n" +
	"\n" +
	"\b_bitrateB\r\n" +
	"\v_view_count\"#\n" +
	"\x11EndSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"r\n" +
	"\x13ListSessionsRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x05R\tchannelId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vpage_number\x18\x03 \x01(\x05R\n" +
	"pageNumber\"\x84\x01\n" +
	"\x14ListSessionsResponse\x123\n" +
	"\bsessions\x18\x01 \x03(\v2\x17.stream.SessionResponseR\bsessions\x127\n" +
	"\tmeta_data\x18\x02 \x01(\v2\x1a.common.PaginationMetadataR\bmetaData\"\x96\x02\n" +
	"\x1dUpdateProcessingStatusRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.stream.StreamStatusH\x00R\x06status\x88\x01\x01\x125\n" +
	"\x14view_count_increment\x18\x03 \x01(\x05H\x01R\x12viewCountIncrement\x88\x01\x01\x121\n" +
	"\x12current_view_count\x18\x04 \x01(\x05H\x02R\x10currentViewCount\x88\x01\x01B\t\n" +
	"\a_statusB\x17\n" +
	"\x15_view_count_incrementB\x15\n" +
	"\x13_current_view_count\".\n" +
	"\x13GetStreamKeyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"5\n" +
	"\x14GetStreamKeyResponse\x12\x1d\n" +
	"\n" +
	"stream_key\x18\x01 \x01(\tR\tstreamKey\"I\n" +
	"\x15ResetStreamKeyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\anew_key\x18\x02 \x01(\tR\x06newKey\"F\n" +
	"\x17GetStaleSessionsRequest\x12+\n" +
	"\x11threshold_seconds\x18\x01 \x01(\x05R\x10thresholdSeconds\";\n" +
	"\x18GetStaleSessionsResponse\x12\x1f\n" +
	"\vsession_ids\x18\x01 \x03(\x03R\n" +
	"sessionIds\">\n" +
	"\x1dUpdateSessionHeartbeatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId*>\n" +
	"\fStreamStatus\x12\v\n" +
	"\aOFFLINE\x10\x00\x12\b\n" +
	"\x04LIVE\x10\x01\x12\f\n" +
	"\bCOMPLETE\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x032\xa4\b\n" +
	"\rStreamService\x12F\n" +
	"\rCreateChannel\x12\x1c.stream.CreateChannelRequest\x1a\x17.stream.ChannelResponse\x12@\n" +
	"\n" +
	"GetChannel\x12\x19.stream.GetChannelRequest\x1a\x17.stream.ChannelResponse\x12F\n" +
	"\rUpdateChannel\x12\x1c.stream.UpdateChannelRequest\x1a\x17.stream.ChannelResponse\x12E\n" +
	"\rDeleteChannel\x12\x1c.stream.DeleteChannelRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\fGetStreamKey\x12\x1b.stream.GetStreamKeyRequest\x1a\x1c.stream.GetStreamKeyResponse\x12H\n" +
	"\x0eResetStreamKey\x12\x1d.stream.ResetStreamKeyRequest\x1a\x17.stream.ChannelResponse\x12F\n" +
	"\rCreateSession\x12\x1c.stream.CreateSessionRequest\x1a\x17.stream.SessionResponse\x12@\n" +
	"\n" +
	"GetSession\x12\x19.stream.GetSessionRequest\x1a\x17.stream.SessionResponse\x12F\n" +
	"\rUpdateSession\x12\x1c.stream.UpdateSessionRequest\x1a\x17.stream.SessionResponse\x12?\n" +
	"\n" +
	"EndSession\x12\x19.stream.EndSessionRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\fListSessions\x12\x1b.stream.ListSessionsRequest\x1a\x1c.stream.ListSessionsResponse\x12W\n" +
	"\x16UpdateProcessingStatus\x12%.stream.UpdateProcessingStatusRequest\x1a\x16.google.protobuf.Empty\x12U\n" +
	"\x10GetStaleSessions\x12\x1f.stream.GetStaleSessionsRequest\x1a .stream.GetStaleSessionsResponse\x12W\n" +
	"\x16UpdateSessionHeartbeat\x12%.stream.UpdateSessionHeartbeatRequest\x1a\x16.google.protobuf.EmptyB\x16Z\x14internal/proto;protob\x06proto3"

var (
	file_stream_proto_rawDescOnce sync.Once
	file_stream_proto_rawDescData []byte
)

func file_stream_proto_rawDescGZIP() []byte {
	file_stream_proto_rawDescOnce.Do(func() {
		file_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stream_proto_rawDesc), len(file_stream_proto_rawDesc)))
	})
	return file_stream_proto_rawDescData
}

var file_stream_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_stream_proto_goTypes = []any{
	(StreamStatus)(0),                     // 0: stream.StreamStatus
	(*ChannelResponse)(nil),               // 1: stream.ChannelResponse
	(*SessionResponse)(nil),               // 2: stream.SessionResponse
	(*CreateChannelRequest)(nil),          // 3: stream.CreateChannelRequest
	(*GetChannelRequest)(nil),             // 4: stream.GetChannelRequest
	(*UpdateChannelRequest)(nil),          // 5: stream.UpdateChannelRequest
	(*DeleteChannelRequest)(nil),          // 6: stream.DeleteChannelRequest
	(*CreateSessionRequest)(nil),          // 7: stream.CreateSessionRequest
	(*GetSessionRequest)(nil),             // 8: stream.GetSessionRequest
	(*UpdateSessionRequest)(nil),          // 9: stream.UpdateSessionRequest
	(*EndSessionRequest)(nil),             // 10: stream.EndSessionRequest
	(*ListSessionsRequest)(nil),           // 11: stream.ListSessionsRequest
	(*ListSessionsResponse)(nil),          // 12: stream.ListSessionsResponse
	(*UpdateProcessingStatusRequest)(nil), // 13: stream.UpdateProcessingStatusRequest
	(*GetStreamKeyRequest)(nil),           // 14: stream.GetStreamKeyRequest
	(*GetStreamKeyResponse)(nil),          // 15: stream.GetStreamKeyResponse
	(*ResetStreamKeyRequest)(nil),         // 16: stream.ResetStreamKeyRequest
	(*GetStaleSessionsRequest)(nil),       // 17: stream.GetStaleSessionsRequest
	(*GetStaleSessionsResponse)(nil),      // 18: stream.GetStaleSessionsResponse
	(*UpdateSessionHeartbeatRequest)(nil), // 19: stream.UpdateSessionHeartbeatRequest
	(*timestamppb.Timestamp)(nil),         // 20: google.protobuf.Timestamp
	(*PaginationMetadata)(nil),            // 21: common.PaginationMetadata
	(*emptypb.Empty)(nil),                 // 22: google.protobuf.Empty
}
var file_stream_proto_depIdxs = []int32{
	20, // 0: stream.ChannelResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: stream.SessionResponse.status:type_name -> stream.StreamStatus
	20, // 2: stream.SessionResponse.start_time:type_name -> google.protobuf.Timestamp
	20, // 3: stream.SessionResponse.end_time:type_name -> google.protobuf.Timestamp
	20, // 4: stream.SessionResponse.last_heartbeat_at:type_name -> google.protobuf.Timestamp
	2,  // 5: stream.ListSessionsResponse.sessions:type_name -> stream.SessionResponse
	21, // 6: stream.ListSessionsResponse.meta_data:type_name -> common.PaginationMetadata
	0,  // 7: stream.UpdateProcessingStatusRequest.status:type_name -> stream.StreamStatus
	3,  // 8: stream.StreamService.CreateChannel:input_type -> stream.CreateChannelRequest
	4,  // 9: stream.StreamService.GetChannel:input_type -> stream.GetChannelRequest
	5,  // 10: stream.StreamService.UpdateChannel:input_type -> stream.UpdateChannelRequest
	6,  // 11: stream.StreamService.DeleteChannel:input_type -> stream.DeleteChannelRequest
	14, // 12: stream.StreamService.GetStreamKey:input_type -> stream.GetStreamKeyRequest
	16, // 13: stream.StreamService.ResetStreamKey:input_type -> stream.ResetStreamKeyRequest
	7,  // 14: stream.StreamService.CreateSession:input_type -> stream.CreateSessionRequest
	8,  // 15: stream.StreamService.GetSession:input_type -> stream.GetSessionRequest
	9,  // 16: stream.StreamService.UpdateSession:input_type -> stream.UpdateSessionRequest
	10, // 17: stream.StreamService.EndSession:input_type -> stream.EndSessionRequest
	11, // 18: stream.StreamService.ListSessions:input_type -> stream.ListSessionsRequest
	13, // 19: stream.StreamService.UpdateProcessingStatus:input_type -> stream.UpdateProcessingStatusRequest
	17, // 20: stream.StreamService.GetStaleSessions:input_type -> stream.GetStaleSessionsRequest
	19, // 21: stream.StreamService.UpdateSessionHeartbeat:input_type -> stream.UpdateSessionHeartbeatRequest
	1,  // 22: stream.StreamService.CreateChannel:output_type -> stream.ChannelResponse
	1,  // 23: stream.StreamService.GetChannel:output_type -> stream.ChannelResponse
	1,  // 24: stream.StreamService.UpdateChannel:output_type -> stream.ChannelResponse
	22, // 25: stream.StreamService.DeleteChannel:output_type -> google.protobuf.Empty
	15, // 26: stream.StreamService.GetStreamKey:output_type -> stream.GetStreamKeyResponse
	1,  // 27: stream.StreamService.ResetStreamKey:output_type -> stream.ChannelResponse
	2,  // 28: stream.StreamService.CreateSession:output_type -> stream.SessionResponse
	2,  // 29: stream.StreamService.GetSession:output_type -> stream.SessionResponse
	2,  // 30: stream.StreamService.UpdateSession:output_type -> stream.SessionResponse
	22, // 31: stream.StreamService.EndSession:output_type -> google.protobuf.Empty
	12, // 32: stream.StreamService.ListSessions:output_type -> stream.ListSessionsResponse
	22, // 33: stream.StreamService.UpdateProcessingStatus:output_type -> google.protobuf.Empty
	18, // 34: stream.StreamService.GetStaleSessions:output_type -> stream.GetStaleSessionsResponse
	22, // 35: stream.StreamService.UpdateSessionHeartbeat:output_type -> google.protobuf.Empty
	22, // [22:36] is the sub-list for method output_type
	8,  // [8:22] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_stream_proto_init() }
func file_stream_proto_init() {
	if File_stream_proto != nil {
		return
	}
	file_common_proto_init()
	file_stream_proto_msgTypes[3].OneofWrappers = []any{}
	file_stream_proto_msgTypes[4].OneofWrappers = []any{}
	file_stream_proto_msgTypes[8].OneofWrappers = []any{}
	file_stream_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stream_proto_rawDesc), len(file_stream_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stream_proto_goTypes,
		DependencyIndexes: file_stream_proto_depIdxs,
		EnumInfos:         file_stream_proto_enumTypes,
		MessageInfos:      file_stream_proto_msgTypes,
	}.Build()
	File_stream_proto = out.File
	file_stream_proto_goTypes = nil
	file_stream_proto_depIdxs = nil
}
